### ISSUE TITLE
syntax error while UpdateRemotePlugin

### ISSUE THREAD

**Issue by yuhuihu** [numirias/semshi#14]
Encountered `SyntaxError` loading plugin at `/Users/yuhui/.local/share/nvim/plugged/semshi/rplugin/python3/semshi: invalid syntax (handler.py, line 234)`
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/neovim/plugin/host.py", line 130, in _load
    module = imp.load_module(name, file, pathname, descr)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/imp.py", line 217, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/yuhui/.local/share/nvim/plugged/semshi/rplugin/python3/semshi/handler.py", line 234
    (id, line, name, self._buf_num), async=True)
```

**Comment by numirias** [comment]
Thanks for reporting!

My first guess is that this is due to a backwards-incompatible [syntax change](https://docs.python.org/3/whatsnew/3.7.html) in Python 3.7:

> `async` and `await` are now reserved keywords.

Since the neovim API is using `async` as parameter name, this violates the 3.7 syntax. I'll let you know when I got that fixed.

**Comment by numirias** [comment]
@yuhuihu Semshi should work fine on 3.7 now. Does this resolve the problem for you?
