### ISSUE TITLE
KeyError: 18446744073709551615

### ISSUE THREAD

**Issue by darthdeus** [numirias/semshi#17]
I'm running into an issue that's possibly related to https://github.com/neovim/python-client/issues/310

```
Error detected while processing function remote#define#notify:
line    6:
E475: Invalid argument: Channel doesn't exist
```

and the logs

```
2018-07-17 21:51:37,048 [INFO @ session.py:request:99] 36041 - 'Received error: [1, b"Key 'semshi#excluded_buffers' not found"]
2018-07-17 21:51:37,049 [INFO @ session.py:request:99] 36041 - 'Received error: [1, b"Key 'semshi#excluded_hl_groups' not found"]
2018-07-17 21:51:37,049 [INFO @ session.py:request:99] 36041 - 'Received error: [1, b"Key 'semshi#mark_selected_nodes' not found"]
2018-07-17 21:51:37,050 [INFO @ session.py:request:99] 36041 - 'Received error: [1, b"Key 'semshi#error_sign' not found"]
2018-07-17 21:51:37,050 [INFO @ session.py:request:99] 36041 - 'Received error: [1, b"Key 'semshi#error_sign_delay' not found"]
2018-07-17 21:51:37,050 [INFO @ session.py:request:99] 36041 - 'Received error: [1, b"Key 'semshi#always_update_all_highlights' not found"]
2018-07-17 21:51:37,051 [INFO @ session.py:request:99] 36041 - 'Received error: [1, b"Key 'semshi#tolerate_syntax_errors' not found"]
2018-07-17 21:51:37,051 [INFO @ session.py:request:99] 36041 - 'Received error: [1, b"Key 'semshi#update_delay_factor' not found"]
2018-07-17 21:51:37,051 [INFO @ session.py:request:99] 36041 - 'Received error: [1, b"Key 'semshi#self_to_attribute' not found"]
2018-07-17 21:51:37,119 [WARNING @ async_session.py:_on_message:83] 36041 - Traceback (most recent call last):
  File ".venv/lib/python3.6/site-packages/neovim/msgpack_rpc/async_session.py", line 80, in _on_message
    self._handlers.get(msg[0], self._on_invalid_message)(msg)
  File ".venv/lib/python3.6/site-packages/neovim/msgpack_rpc/async_session.py", line 101, in _on_response
    self._pending_requests.pop(msg[1])(msg[2], msg[3])
KeyError: 18446744073709551615
```

This happens basically all the time when moving around in a file.

**Comment by numirias** [comment]
Thanks for reporting! I suspect that in this specific case, you *may* see this bug because an error with Semshi itself is cause a high volume of RPC traffic, only coincidentally triggering that RPC bug. So I think this can be circumvented by finding out why you get the initial Semshi-related key errors (`Key 'semshi#excluded_buffers' not found`, etc.).

Do you mind sharing the neovim frontend, OS and maybe the config you're using?

**Comment by numirias** [comment]
@darthdeus I'm sorry, blaming the initial key errors was a red herring. They are fine (if they are just raised once at the beginning of a session when Semshi initializes the options). It's an innocuous side effect of this line in `plugin.py`:
```python
val = vim.vars.get('semshi#' + key, val_default)
```

So we need to investigate why you get that `KeyError: 18446744073709551615` RPC error anyway.

- Does it still occur if you're using a minimal config?

- > This happens basically all the time when moving around in a file.

  Does that happen with any Python file of any size and immediately on startup or does it sometimes take a bit to occur?

- Do you have the chance to test that config on another machine? If so, does the bug reproduce there?

- Just to clarify again, are using vim in the terminal or a particular frontend (GUI)?

- Finally, do you mind trying to go into `handler.py`, set `batch_size` inside `_call_atomic_async()` to a smaller value and see if the error disappears? (It's [this line](https://github.com/numirias/semshi/blob/e386dbf7759efdd24cb5740f4cfd9361f0487eae/rplugin/python3/semshi/handler.py#L272).)

**Comment by darthdeus** [comment]
- Does it still occur if you're using a minimal config?

It seems to be related to deoplete.vim. I've tried for a bit with the following config:

```vim
set nocompatible
source ~/.dotfiles/third-party/vim-plug/plug.vim

call plug#begin("~/.dotfiles/test-plugs")

Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'zchee/deoplete-jedi'
Plug 'numirias/semshi', {'do': ':UpdateRemotePlugins'}
Plug 'davidhalter/jedi-vim'

" let g:deoplete#enable_at_startup = 1

call plug#end()
```

If I uncomment `let g:deoplete#enable_at_startup = 1` I get the error rather quickly. Sometimes even immediately. But when it is disabled the issue doesn't occur. At the same time it doesn't seem to occur when I don't include semshi.

* Does that happen with any Python file of any size and immediately on startup or does it sometimes take a bit to occur?

It doesn't happen at startup, but it happens at various times. Sometimes I hit `O` and I get an error, and sometimes I can edit for say 30-60 seconds and nothing breaks.

It does happen to other files, but I wasn't yet able to reproduce it in small ones. I'll comment if I can. However it does happen even at the beginning of large files (when not scrolled down).

* Do you have the chance to test that config on another machine? If so, does the bug reproduce there?

I didn't yet. I can test later if it's still needed.

* Just to clarify again, are using vim in the terminal or a particular frontend (GUI)?

Yes, I am using Neovim in the terminal (inside tmux), no GUI.

* Finally, do you mind trying to go into handler.py, set batch_size inside _call_atomic_async() to a smaller value and see if the error disappears? (It's this line.)

Updating to `20` caused this:

```
error caught in async handler '/Users/arnoljak/.dotfiles/test-plugs/semshi/rplugin/python3/semshi:autocmd:CursorMovedI:*.py []'
Traceback (most recent call last):
  File "/Users/arnoljak/.dotfiles/test-plugs/semshi/rplugin/python3/semshi/plugin.py", line 21, in wrapper
    func(self)
  File "/Users/arnoljak/.dotfiles/test-plugs/semshi/rplugin/python3/semshi/plugin.py", line 88, in event_cursor_moved_insert
    self._update_viewport()
  File "/Users/arnoljak/.dotfiles/test-plugs/semshi/rplugin/python3/semshi/plugin.py", line 180, in _update_viewport
    stop = self._vim.eval('line("w$")')
  File "/Users/arnoljak/.pyenv/versions/3.6.5/lib/python3.6/site-packages/neovim/api/nvim.py", line 280, in eval
    return self.request('nvim_eval', string, **kwargs)
  File "/Users/arnoljak/.pyenv/versions/3.6.5/lib/python3.6/site-packages/neovim/api/nvim.py", line 170, in request
    res = self._session.request(name, *args, **kwargs)
  File "/Users/arnoljak/.pyenv/versions/3.6.5/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 91, in request
    v = self._yielding_request(method, args)
  File "/Users/arnoljak/.pyenv/versions/3.6.5/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 158, in _yielding_request
    self._async_session.request(method, args, response_cb)
  File "/Users/arnoljak/.pyenv/versions/3.6.5/lib/python3.6/site-packages/neovim/msgpack_rpc/async_session.py", line 45, in request
    self._msgpack_stream.send([0, request_id, method, args])
  File "/Users/arnoljak/.pyenv/versions/3.6.5/lib/python3.6/site-packages/neovim/msgpack_rpc/msgpack_stream.py", line 35, in send
    self.loop.send(self._packer.pack(msg))
  File "/Users/arnoljak/.pyenv/versions/3.6.5/lib/python3.6/site-packages/neovim/msgpack_rpc/event_loop/base.py", line 118, in send
    self._send(data)
  File "/Users/arnoljak/.pyenv/versions/3.6.5/lib/python3.6/site-packages/neovim/msgpack_rpc/event_loop/asyncio.py", line 107, in _send
    self._transport.write(data)
  File "/Users/arnoljak/.pyenv/versions/3.6.5/lib/python3.6/asyncio/unix_events.py", line 569, in write
    self._loop._add_writer(self._fileno, self._write_ready)
  File "/Users/arnoljak/.pyenv/versions/3.6.5/lib/python3.6/asyncio/selector_events.py", line 307, in _add_writer
    (reader, handle))
  File "/Users/arnoljak/.pyenv/versions/3.6.5/lib/python3.6/selectors.py", line 261, in modify
    key = self.register(fileobj, events, data)
  File "/Users/arnoljak/.pyenv/versions/3.6.5/lib/python3.6/selectors.py", line 536, in register
    key = super().register(fileobj, events, data)
  File "/Users/arnoljak/.pyenv/versions/3.6.5/lib/python3.6/selectors.py", line 241, in register
    .format(fileobj, key.fd))
KeyError: '1 (FD 1) is already registered'
```

but updating to `200` does seem to help. I haven't run into the error yet. I'll post in case I do.

**Comment by darthdeus** [comment]
A small update, just ran into the same error with `batch_size` set to `200`, so I guess it only prolonged the error.

**Comment by bfredl** [comment]
This is a bug in neovim. Errors in `async_` requests wasn't sent back to clients in a meaningful way (18446744073709551615 is an internal sentinel value that shouldn't be exposed).

Next Nvim release 0.3.2 (+ accompanying pynvim release) will fix this.
