### ISSUE TITLE
Not working on python 3.6 and earlier

### ISSUE THREAD

**Issue by cbosdo** [numirias/semshi#24]
I still don't have python 3.7 in my distro, and [commit 7116e72dcb7baeb27165cd5cf8384e192596902][0] introduces async_ keyword which triggers an error on pre-3.7 pythons. Would there be a way to keep semshi compatible with all 3.xxx pythons?

    error caught in async handler '/home/cbosdo/.config/nvim/plugged/semshi/rplugin/python3/semshi:autocmd:CursorMoved:*.py []'                                                                             
    Traceback (most recent call last):
      File "/home/cbosdo/.config/nvim/plugged/semshi/rplugin/python3/semshi/plugin.py", line 21, in wrapper
        func(self)
      File "/home/cbosdo/.config/nvim/plugged/semshi/rplugin/python3/semshi/plugin.py", line 81, in event_cursor_moved
        self._update_viewport()
      File "/home/cbosdo/.config/nvim/plugged/semshi/rplugin/python3/semshi/plugin.py", line 181, in _update_viewport
        self._cur_handler.viewport(start, stop)
      File "/home/cbosdo/.config/nvim/plugged/semshi/rplugin/python3/semshi/handler.py", line 55, in viewport
        self._add_visible_hls()
      File "/home/cbosdo/.config/nvim/plugged/semshi/rplugin/python3/semshi/util.py", line 19, in wrapper
        res = func(*args, **kwargs)
      File "/home/cbosdo/.config/nvim/plugged/semshi/rplugin/python3/semshi/handler.py", line 169, in _add_visible_hls
        self._add_hls(nodes_to_hl(visible))
      File "/home/cbosdo/.config/nvim/plugged/semshi/rplugin/python3/semshi/util.py", line 19, in wrapper
        res = func(*args, **kwargs)
      File "/home/cbosdo/.config/nvim/plugged/semshi/rplugin/python3/semshi/handler.py", line 254, in _add_hls
        [('nvim_buf_add_highlight', (buf, *n)) for n in node_or_nodes])
      File "/home/cbosdo/.config/nvim/plugged/semshi/rplugin/python3/semshi/handler.py", line 274, in _call_atomic_async
        self._vim.api.call_atomic(calls[i:i + batch_size], async_=True)
      File "/usr/lib/python3.6/site-packages/neovim/api/nvim.py", line 140, in request
        res = self._session.request(name, *args, **kwargs)
      File "/usr/lib/python3.6/site-packages/neovim/msgpack_rpc/session.py", line 86, in request
        .format(', '.join(kwargs.keys())))
    ValueError: request got unsupported keyword argument(s): async_

[0]: https://github.com/numirias/semshi/commit/27116e72dcb7baeb27165cd5cf8384e192596902

**Comment by numirias** [comment]
Thanks for reporting! That's odd because the commit you referenced should not break anything for Python < 3.7. (I'm testing against 3.5, 3.6, 3.7). What's your installed Neovim Python client version? (`$ pip show neovim`)?

**Comment by numirias** [comment]
Unfortunately, 0.2.4 is outdated and I don't intend to support it. Do you mind upgrading to 0.2.6?

(The newest release actually is 0.3.0, however there are currently some issues independent from your report, so don't upgrade to that just yet. See #25)

**Comment by cbosdo** [comment]
Looks like [0.2.6 is in the pipe][0] and will soon be in openSUSE Tumbleweed repos. I'll test with it once it's out.

[0]: https://build.opensuse.org/request/show/646075

**Comment by wookayin** [comment]
I have bumped into this issue before, and the correct solution was to install neovim python client 0.2.6 (`pip install neovim==0.2.6`).

**Comment by numirias** [comment]
I'll close then. @cbosdo Feel free to reopen if you run into issues with an updated Python client version.

**Comment by cbosdo** [comment]
Just updated to 0.2.6 and semshi now works like a charm. Thanks guys for the info!
