### ISSUE TITLE
Neovim daily fails to UpdateRemotePlugins for semshi

### ISSUE THREAD

**Issue by BonaBeavis** [numirias/semshi#32]
Neovim depreciates the neovim remote plugin in favor of pynvim. On the latest NVIM v0.3.2-dev `UpdateRemotePlugins' does not work for semshi.

```
Encountered ModuleNotFoundError loading plugin at /home/beavis/.vim/bundle/semshi/rplugin/python3/semshi:
No module named 'neovim'
Traceback (most recent call last):
  File "/home/beavis/.virtualenvs/neovim3/lib/python3.6/site-packages/pynvim/plugin/host.py", line 135, in
 _load
    module = imp.load_module(name, file, pathname, descr)
  File "/home/beavis/.virtualenvs/neovim3/lib/python3.6/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/home/beavis/.virtualenvs/neovim3/lib/python3.6/imp.py", line 217, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 684, in _load
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
ModuleNotFoundError: No module named 'neovim'
```

Here is my output for ':checkhealth'
https://gist.github.com/BonaBeavis/b4afcc37f71363b1a58608919450ff4c ( the // in the paths are from my removed username)

**Comment by BonaBeavis** [comment]
Found the problem:

https://github.com/neovim/neovim/wiki/Following-HEAD#20181118

I leave this open, because others could run into this.

**Comment by numirias** [comment]
Thanks for reporting! I'll fix the module name ASAP.
