### ISSUE TITLE
goto error not working

### ISSUE THREAD

**Issue by tbrodbeck** [numirias/semshi#37]
Hey, love your Plugin! 
It used to work for me but right now I got an error when using `goto error` (the universe has humor lol) and it does nothing. Here the error trace:
`Error detected while processing function remote#define#request:                                                                                                                                        
line    2:
error caught in request handler '/home/tbrodbeck/.config/nvim/plugged/semshi/rplugin/python3/semshi:command:Semshi [['goto', 'error']]':
Traceback (most recent call last):
  File "/home/tbrodbeck/.config/nvim/plugged/semshi/rplugin/python3/semshi/plugin.py", line 139, in cmd_semshi
    func(self, *args[1:])
  File "/home/tbrodbeck/.config/nvim/plugged/semshi/rplugin/python3/semshi/plugin.py", line 38, in wrapper
    func(self, *args, **kwargs)
  File "/home/tbrodbeck/.config/nvim/plugged/semshi/rplugin/python3/semshi/plugin.py", line 183, in goto
    self._cur_handler.goto(*args, **kwargs)
  File "/home/tbrodbeck/.config/nvim/plugged/semshi/rplugin/python3/semshi/handler.py", line 332, in goto
    self._goto_error()
  File "/home/tbrodbeck/.config/nvim/plugged/semshi/rplugin/python3/semshi/handler.py", line 366, in _goto_error
    self._vim.current.window.cursor = self._error_pos(error)
  File "/home/tbrodbeck/.config/nvim/plugged/semshi/rplugin/python3/semshi/handler.py", line 372, in _error_pos
    len(self._parser.lines[error.lineno - 1]))) - 1
IndexError: list index out of range
Press ENTER or type command to continue`

Best, Till

**Comment by numirias** [comment]
Thanks for reporting!

Can you provide a sample file on which `goto error` fails? Does it fail reliably or are other steps necessary to reproduce?

**Comment by tbrodbeck** [comment]
I am really sorry for my bad bug reporting. I just fixed the error and I can not reproduce it myself. If it happens again, I will report it here immediately.
