### ISSUE TITLE
pynvim.api.common.NvimError

### ISSUE THREAD

**Issue by Lugges991** [numirias/semshi#68]
Every time I try to open a .py file I get the following error:
`Error detected while processing function <SNR>59_filetype_changed[4]..remote#define#CommandBootstrap[5]..remote#define#request:
line    2:
error caught in request handler '/root/.config/nvim/plugged/semshi/rplugin/python3/semshi:command:Semshi [['enable']]':
Traceback (most recent call last):
  File "/root/.config/nvim/plugged/semshi/rplugin/python3/semshi/plugin.py", line 126, in cmd_semshi
    func(self, *args[1:])
  File "/root/.config/nvim/plugged/semshi/rplugin/python3/semshi/plugin.py", line 29, in wrapper
    self._init_with_vim()
  File "/root/.config/nvim/plugged/semshi/rplugin/python3/semshi/plugin.py", line 61, in _init_with_vim
    self._options = Options(self._vim)
  File "/root/.config/nvim/plugged/semshi/rplugin/python3/semshi/plugin.py", line 269, in __init__
    val = vim.vars.get('semshi#' + key, val_default)
  File "/usr/local/lib/python3.6/dist-packages/pynvim/api/common.py", line 138, in get
    return self.__getitem__(key)
  File "/usr/local/lib/python3.6/dist-packages/pynvim/api/common.py", line 110, in __getitem__
    raise transform_keyerror(exc)
  File "/usr/local/lib/python3.6/dist-packages/pynvim/api/common.py", line 108, in __getitem__
    return self._get(key)
  File "/usr/local/lib/python3.6/dist-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pynvim/msgpack_rpc/session.py", line 102, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Key 'semshi#excluded_hl_groups' not found
`

Then after neovim started, syntax highlighting is not working.
I also reproduced this error with a minimal config of just semshi.

**Comment by ywpkwon** [comment]
I've been using `semshi` without any problem, but I setup neovim to my new Ubuntu 18.04 computer today and I got similar error about "pynvim.api.common.NvimError" when openging a .py file:
````
Error detected while processing function <SNR>50_filetype_changed[4]..remote#define#CommandBootstrap[5]..remote#define#request:
line    2:
error caught in request handler '/home/paul/.vim/plugged/semshi/rplugin/python3/semshi:command:Semshi [['enable']]':
Traceback (most recent call last):
  File "/home/paul/.vim/plugged/semshi/rplugin/python3/semshi/plugin.py", line 126, in cmd_semshi
    func(self, *args[1:])
  File "/home/paul/.vim/plugged/semshi/rplugin/python3/semshi/plugin.py", line 29, in wrapper
    self._init_with_vim()
  File "/home/paul/.vim/plugged/semshi/rplugin/python3/semshi/plugin.py", line 61, in _init_with_vim
    self._options = Options(self._vim)
  File "/home/paul/.vim/plugged/semshi/rplugin/python3/semshi/plugin.py", line 269, in __init__
    val = vim.vars.get('semshi#' + key, val_default)
  File "/home/paul/.local/lib/python3.6/site-packages/pynvim/api/common.py", line 138, in get
    return self.__getitem__(key)
  File "/home/paul/.local/lib/python3.6/site-packages/pynvim/api/common.py", line 110, in __getitem__
    raise transform_keyerror(exc)
  File "/home/paul/.local/lib/python3.6/site-packages/pynvim/api/common.py", line 108, in __getitem__
    return self._get(key)
  File "/home/paul/.local/lib/python3.6/site-packages/pynvim/api/nvim.py", line 182, in request
    res = self._session.request(name, *args, **kwargs)
  File "/home/paul/.local/lib/python3.6/site-packages/pynvim/msgpack_rpc/session.py", line 104, in request
    raise self.error_wrapper(err)
pynvim.api.common.NvimError: Key 'semshi#mark_selected_nodes' not found
````

**Comment by ywpkwon** [comment]
@Lugges991 I think I found a solution. This issue seems also related to https://github.com/numirias/semshi/issues/17. In my case, I upgraded neovim to v0.4.3 and the error disappeared.

For information, to upgrade neovim (I'm using Ubuntu and `apt` only provides v0.2.2): 
````
sudo apt remove neovim        # remove ubuntu official package
curl -LO https://github.com/neovim/neovim/releases/download/stable/nvim.appimage
chmod u+x nvim.appimage
sudo mv nvim.appimage /usr/local/bin/nvim
````
